package pojo;
// Generated Oct 15, 2022 12:07:25 AM by Hibernate Tools 4.3.1

import dao.staffDAO;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * Staff generated by hbm2java
 */
@ManagedBean (name = "fdwi")
public class Staff  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
         public String login() {
        staffDAO sd = new staffDAO();
        List<Staff> st = sd.getBy(username, password);
        try {
            if (!st.isEmpty()) {
                username = st.get(0).username;
                password = st.get(0).password;
                return "dashboard";
            } else{
                
            }
        } catch (Exception e) {
            System.out.println(e);
            username = "";
            password = "";
        }
        return "index";
    }
    public String logout() {  
	return "index";
    }
    public Staff() {
    }

    public Staff(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


